### ISSUE TITLE
Don't highlight with highlight checked by nothing in the filter

### ISSUE THREAD

**Issue by Nedlinin** [Critical-Impact/InventoryTools#26] opened 2021-11-02 23:22 UTC
Rather than highlighting every icon in my inventory if highlight is checked but nothing is typed in the filters, how about highlighting nothing until some "real" filter is applied?

**Comment by Critical-Impact** [comment] 2022-01-19 06:20
Duplicate of #30 
Check your background filter, I'm making it not save the background filter at all so this won't happen regardless
Will close issue once new build is out

**Closed** 2022-01-24 08:19 UTC
